In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df=pd.read_csv("spam.csv" , encoding='latin-1')

In [7]:
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [8]:
df.shape

(5572, 5)

In [10]:
df.describe()

v1                      v2  \
count   5572                    5572   
unique     2                    5169   
top      ham  Sorry, I'll call later   
freq    4825                      30   

                                               Unnamed: 2  \
count                                                  50   
unique                                                 43   
top      bt not his girlfrnd... G o o d n i g h t . . .@"   
freq                                                    3   

                   Unnamed: 3 Unnamed: 4  
count                      12          6  
unique                     10          5  
top      MK17 92H. 450Ppw 16"    GNT:-)"  
freq                        2          2

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [12]:
df['v1'].value_counts().sum()

5572

In [14]:
df = df[['v1', 'v2']]
df.columns = ['label', 'message']

# encoded labels

In [16]:
df['label'] = df['label'].map({'ham': 0, 'spam': 1})

C:\Users\HP\AppData\Local\Temp\ipykernel_14624\2851929608.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['label'] = df['label'].map({'ham': 0, 'spam': 1})


In [17]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(df['message'], df['label'], test_size=0.2, random_state=42)

# Tfidf vectorizer

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [22]:
tfidf_vectorizer = TfidfVectorizer(max_features=5000)

X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)

X_test_tfidf = tfidf_vectorizer.transform(X_test)

In [23]:
print(X_train_tfidf)

  (0, 2238)	0.37141508790909694
  (0, 1544)	0.27805800984696366
  (0, 4940)	0.27805800984696366
  (0, 2345)	0.15957326527314455
  (0, 2382)	0.19039045440482874
  (0, 2092)	0.1427846955407011
  (0, 796)	0.27364197602032636
  (0, 2177)	0.3610761139104894
  (0, 2231)	0.1490192872410537
  (0, 476)	0.1691110673895041
  (0, 1595)	0.2246505803613607
  (0, 3721)	0.21083615486777577
  (0, 619)	0.37141508790909694
  (0, 3209)	0.26710534096823246
  (0, 4052)	0.12427677819754168
  (0, 1700)	0.1356900314797867
  (0, 2283)	0.1765978619216568
  (1, 2463)	0.186854702151232
  (1, 0)	0.2434043271470486
  (1, 1755)	0.10164430659147042
  (1, 4047)	0.11591125876695065
  (1, 767)	0.28051722294058273
  (1, 3905)	0.2707988583394415
  (1, 2246)	0.28051722294058273
  (1, 167)	0.2632607091194256
  :	:
  (4452, 712)	0.17411912679772312
  (4452, 4172)	0.11354620000772266
  (4452, 4418)	0.20423588938425785
  (4452, 2092)	0.16116384880245432
  (4453, 3611)	0.5422825367621465
  (4453, 1889)	0.564721783565922
  (4453,

In [27]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [28]:
from sklearn.naive_bayes import MultinomialNB

In [29]:
nb = MultinomialNB()
nb.fit(X_train_tfidf, y_train)
nb_pred = nb.predict(X_test_tfidf)

In [30]:
print("Naive Bayes Classifier:")
print("Accuracy Score:", accuracy_score(y_test, nb_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, nb_pred))
print("Classification Report:\n", classification_report(y_test, nb_pred))

Naive Bayes Classifier:
Accuracy Score: 0.9668161434977578
Confusion Matrix:
 [[965   0]
 [ 37 113]]
Classification Report:
               precision    recall  f1-score   support

           0       0.96      1.00      0.98       965
           1       1.00      0.75      0.86       150

    accuracy                           0.97      1115
   macro avg       0.98      0.88      0.92      1115
weighted avg       0.97      0.97      0.96      1115



# Logistic Regression

In [34]:
from sklearn.linear_model import LogisticRegression

In [35]:
lr = LogisticRegression()
lr.fit(X_train_tfidf, y_train)
lr_pred = lr.predict(X_test_tfidf)

In [36]:
print("Logistic Regression:")
print("Accuracy Score:", accuracy_score(y_test, lr_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, lr_pred))
print("Classification Report:\n", classification_report(y_test, lr_pred))

Logistic Regression:
Accuracy Score: 0.967713004484305
Confusion Matrix:
 [[964   1]
 [ 35 115]]
Classification Report:
               precision    recall  f1-score   support

           0       0.96      1.00      0.98       965
           1       0.99      0.77      0.86       150

    accuracy                           0.97      1115
   macro avg       0.98      0.88      0.92      1115
weighted avg       0.97      0.97      0.97      1115



# Support Vector Machine

In [37]:
from sklearn.svm import SVC

In [38]:
svm = SVC()
svm.fit(X_train_tfidf, y_train)
svm_pred = svm.predict(X_test_tfidf)

In [39]:
print("Support Vector Machine:")
print("Accuracy Score:", accuracy_score(y_test, svm_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, svm_pred))
print("Classification Report:\n", classification_report(y_test, svm_pred))

Support Vector Machine:
Accuracy Score: 0.9802690582959641
Confusion Matrix:
 [[965   0]
 [ 22 128]]
Classification Report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99       965
           1       1.00      0.85      0.92       150

    accuracy                           0.98      1115
   macro avg       0.99      0.93      0.95      1115
weighted avg       0.98      0.98      0.98      1115

